### ISSUE TITLE
bug in _scan-job.tpl?

### ISSUE THREAD

**Issue by corbosman** [datreeio/admission-webhook-datree#317]
Hi, I ran into an issue where I could not install datree using fluxcd. I got this error:

```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 42: mapping key "seccompProfile" already defined at line 40
```

This seems to be caused by scan-job.tpl which defines seccompProfile at line 67, but just before it loads values.yaml which also includes seccompProfile. It might be a bug in fluxcd helm-controller. I was able to workaround it by defining seccompProfile: null in my values config.

**Comment by noaabarki** [comment]
Hi there @corbosman, 

I noticed that you configured the HelmRepository in the `datree` namespace, but in the `HelmRelease`, you pulled it from the `flux-system` namespace. Additionally, you configured the `HelmRelease` in the `flux-system` namespace. Can you please explain why you did this? Is it possible that you accidentally configured some of the namespaces incorrectly? 

I have updated the resources to use the `datree` namespace. Please try installing the chart using the following resources and let me know if it works. 

```apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: admission-webhook-hr-datree
  namespace: datree
spec:
  releaseName: datree-webhook
  targetNamespace: datree
  chart:
    spec:
      chart: datree-admission-webhook
      sourceRef:
        kind: HelmRepository
        name: admission-webhook-datree
        namespace: datree
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    datree:
      token: "69e5e797-7554-4a43-bbd7-d973a959afc9"
      clusterName: "minikube"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: admission-webhook-datree
  namespace: datree
spec:
  interval: 30m
  url: https://datreeio.github.io/admission-webhook-datree
```

**Comment by corbosman** [comment]
That makes no difference, I put all "flux" resources in the flux-system namespace. But I could also put it in datree namespace.  It's kinda arbitrary. It's probably better to put the release in the datree namespace. 

```targetNamespace: datree```

That makes sure the app itself gets installed in datree namespace. And this works fine, im running datree right now using the workaround. It could very well be that the actual bug is inside the FluxCD Helmcontroller, that it can't handle duplicate keys like you're currently creating with seccompProfile.

**Comment by noaabarki** [comment]
I attempted to install datree via FluxCD, using the resources configured in the way you specified. However, the installation failed due to the following error: "failed to get source: `HelmRepository.source.toolkit.fluxcd.io` "datree-webhook" not found". This occurred both with and without the `seccompProfile`. However, after updating the resources with the correct namespaces, everything worked fine.

It's possible that FluxCD has an issue with duplicate keys in the helm chart, as discussed [here](https://github.com/fluxcd/helm-controller/issues/283). However, this shouldn't affect the datree helm chart. Can you explain why you believe the seccompProfile is duplicated?

**Comment by corbosman** [comment]
From _scan_job.tpl:

```yaml
          securityContext:
            {{- with .Values.securityContext }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
            seccompProfile:
              type: RuntimeDefault
              ```
              
  Then from your default values.yaml (which is include above I guess?)
  ```
  securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 25000
  capabilities:
    drop: [ "ALL" ]
  seccompProfile:
    type: RuntimeDefault
    ```
    
    As you can see, seccompProfile is added twice.
